### ISSUE TITLE
PIC chip Confirmation

### ISSUE THREAD

**Issue by CrasherCourse** [teslaworksumn/HeadMaster#10]
@tylrtrmbl Which PIC chip are we using?  I thought we were using the PIC18F14K50 but, Rachael said we weren't.

**Comment by taylortrimble** [comment]
I think there is something about this in #3 too.

**Comment by taylortrimble** [comment]
Lets move the conversation over there

**Comment by CrasherCourse** [comment]
So if we're not using that PIC what are we going to use?

**Comment by taylortrimble** [comment]
Sorry @CrasherCourse, you were right about this issue. I had a conversation with @mistressoftheelectron about PICs, and she said that it would be better for us to use the PIC18F2620 because it can take 5 volt power. It shouldn't change our code at all, but if it does it will be very minor. Actually, this is closer to the chip we used for the light show (which is the basis for our code now) so we may have saved ourselves some headache.

Either way, we should finalize this here since John and Kevan won't be at the meeting. So if @aterlumen and @John-Phillips don't disagree I say we develop for the PIC18F2620 from now on like Kyle and Rachel discussed.

**Comment by kevana** [comment]
No objections from me.

**Comment by John-Phillips** [comment]
Let's do this!

**Comment by CrasherCourse** [comment]
@tylrtrmbl Ok, so @mistressoftheelectron asked me to order some sample chips.  Instead of 2620, she asked me to get 2685.  According to her, she already spoke with @tylrtrmbl about the change and that these chips are like the 2620 just with more RAM and EPROM.

Is this true?  Cause, I already ordered the samples.

**Comment by taylortrimble** [comment]
_Sigh_. No, we talked about the 2620 having more RAM and EEPROM over the 24J10, but not the 2685 having more RAM and EEPROM over the 2620.

In other words,
24J10 :arrow_right: 2620 :ok: 
2620 :arrow_right: 2685 :question: 

The 2685 isn't available as a breadboard part, which means we're reliant on PCB runs to test our circuit. I don't know if I'm a fan of that for more Program Memory and RAM we won't use.

**Comment by taylortrimble** [comment]
However, switching pinouts if you've already planned the hardware schematic with the 2685 is a big backtrack, so we'll make do with testing with a different chip on breadboard vs PCB if we must.

**Comment by taylortrimble** [comment]
AAAAND I'm wrong; both are available as DIP components. In that case, from a software perspective it doesn't matter at all I think.

Thank you @CrasherCourse!

**Comment by CrasherCourse** [comment]
I did order some sample DIP chips along with the PCB ones so @tylrtrmbl can get a look at it hopefully this week.
Luckily the pin diagrams are essentially the same and the XCP compiler eliminates the need for specific chip header.

The problem is that some names of register bits are labeled slightly differently for the MSSP.
And EUSART uses SCKP bit in place of RXDTP and TXCKP.

I can still get some samples of the 2620 chips if need be.

**Comment by taylortrimble** [comment]
Yes, that sounds good; I'll compile for PIC18F2685 in my `xc8` branch and if there's any build errors I'll open an issue. Thank you!
