### ISSUE TITLE
Code Licensing

### ISSUE THREAD

**Issue by kevana** [teslaworksumn/HeadMaster#20]
All of our homegrown source code should post a license on it. 
GPL
LGPL
MIT / X11
BSD
Apache
Eclipse
Mozilla Public
etc.

Thoughts?

**Comment by CrasherCourse** [comment]
While I have 0 experience with licensing.
GPL looks like it give receivers of our code the freedom to modify and distribute our code.

@aterlumen are you seeing duplicate issues?

**Comment by kevana** [comment]
Yep, it wasn't showing up in my issue view (still isn't), but it obviously exists now.

**Comment by taylortrimble** [comment]
Not anymore, I got rid of them. That was weird.

I've got experience here:
1. First we have to decide whether or not to go open source. That will depend on how you guys feel. I'm fine with it.
2. Next, we'll have to determine if we're assholes or not.
   - Assholes like to pick the GPL (no offense Kyle, but don't worry, you won't pick it. Here's why.) The GPL means that if anyone ever touches even a tiny part of our code, their entire project needs to be open sourced as well. This prevents anyone in the industry from using our code. So if we want our code "open" in the sense of "anyone can use it" the GPL is bad.
   - Non-assholes have a smorgasbord of licenses to pick from, but almost always go MIT or Apache. BSD too, but it and MIT are basically identical and MIT is more "noticed."
3. We'll decide how paranoid we are
   - If we are worried people will sue us for our software not working and fucking up their shit, we'd go with Apache. It is very protective of us, while still letting anyone use our code.
   - MIT License also protects us, just not as explicity.

My favorite by far is the MIT license, because it doesn't prevent people working on commercial software from using our code, it is way shorter than the Apache license and protects us well enough, and -- heres the kicker -- it's the de facto license that when people see it, they say "I don't have to worry about this, I can just use this code." It's like [this license](http://en.wikipedia.org/wiki/WTFPL), but more legit. :stuck_out_tongue_closed_eyes: 

Let me know what you guys think too though. Rant over!

**Comment by taylortrimble** [comment]
@aterlumen You may have had filters engaged in the issues view.

**Comment by kevana** [comment]
I was leaning towards open source under MIT. Also, should the copyright notice name an individual or Tesla Works? Along those lines, can a student group even hold copyright?

**Comment by taylortrimble** [comment]
This is a complicated issue. Technically, the minute you write a line of code, the copyright goes to you. We could technically write `// Copyright (c) 2012 The magical enchanted panda under my couch. All rights reserved.` And the copyright still belongs to _you_ (for the lines of code you wrote), _me_ for the lines of code I wrote, and so on. Some source files you'll see

`// Copyright (c) 2012 Kevan Ahlquist, Taylor Trimble, Kyle Michaels, Larry Offthestreet, Paula Abdul. All rights reserved.`

Unfortunately, it gets long and its complicated. So, we merge the enchanged panda under the couch idea with the idea above and say `// Copyright (c) 2012 Some name that acts as an identifier for the group of people who are working on the file.`

More commonly for open source projects, a single person gets all the copyright, and no one cares because it's under a permissive license.

My vote:
`// Copyright (c) 2012 Tesla Works.`
It's simple and works.

**Comment by taylortrimble** [comment]
I'd also like to hear @CrasherCourse's opinion on open sourcing the project

**Comment by CrasherCourse** [comment]
I don't mind open source under MIT.  I don't think we'll be selling this code.

I feel licensing under TW would be the best and allow other members to use this code in the future without any legal issues.

**Comment by taylortrimble** [comment]
Anyone at all can use it, no matter what we do! :smile: If we find out later that Tesla Works actually doesn't work we can just pile it onto Kevan
`// Copyright (c) 2012 Kevan Ahlquist.`

**Comment by CrasherCourse** [comment]
I second plan B, copyright to Kevan if not Tesla Works.
