### ISSUE TITLE
What DMX Software should we use?

### ISSUE THREAD

**Issue by CrasherCourse** [teslaworksumn/HeadMaster#47]
As the the title asks any ideas on what software we should use to run the show.

We need something that can run multiple audio files, one for each head.

I not sure if the light show software does so or not, which is why I am asking.

**Comment by taylortrimble** [comment]
Right now we have a thread running on the Basecamp for this, since it's not specifically part of the HeadMaster code (our implementation doesn't care what drives it, as long as it's DMX). You can catch the discussion over there! A lot has been thrown around, and right now the idea is that we're rolling our own, but that was when we were planning on Sequence existing. We'll probably use light-o-rama instead then.
